import type { ProtocolDefinition } from "./types";

export const DEFAULT_PROTOCOLS: ProtocolDefinition[] = [
  {
    id: "vless",
    label: "VLESS",
    icon: "Zap",
    category: "user",
    hasUsers: false,
    hasStream: true,
    hasSecurity: true,
    hasSniffing: true,
    description: "Stateless, lightweight. Pair with Reality or TLS + xtls-rprx-vision",
  },
  {
    id: "vmess",
    label: "VMess",
    icon: "Hexagon",
    category: "user",
    hasUsers: true,
    hasStream: true,
    hasSecurity: true,
    hasSniffing: true,
    description: "Stateful, dynamic encryption. Good for CDN/WebSocket setups",
  },
  {
    id: "trojan",
    label: "Trojan",
    icon: "Shield",
    category: "user",
    hasUsers: true,
    hasStream: true,
    hasSecurity: true,
    hasSniffing: true,
    description: "Mimics HTTPS. Password auth. Requires TLS or Reality",
  },
  {
    id: "shadowsocks",
    label: "Shadowsocks",
    icon: "Lock",
    category: "user",
    hasUsers: false,
    hasStream: true,
    hasSecurity: true,
    hasSniffing: true,
    description: "Simple cipher. Best for UDP or 2022 methods. Reality is not supported — use VLESS for that.",
  },
  {
    id: "http",
    label: "HTTP",
    icon: "Globe",
    category: "advanced",
    hasUsers: false,
    hasStream: false,
    hasSecurity: false,
    hasSniffing: true,
    description: "HTTP CONNECT proxy inbound",
  },
  {
    id: "socks",
    label: "SOCKS",
    icon: "Network",
    category: "advanced",
    hasUsers: false,
    hasStream: false,
    hasSecurity: false,
    hasSniffing: true,
    description: "SOCKS4/5 proxy inbound",
  },
  {
    id: "mixed",
    label: "Mixed",
    icon: "Shuffle",
    category: "advanced",
    hasUsers: false,
    hasStream: false,
    hasSecurity: false,
    hasSniffing: true,
    description: "HTTP + SOCKS on same port",
  },
  {
    id: "wireguard",
    label: "WireGuard",
    icon: "KeyRound",
    category: "advanced",
    hasUsers: false,
    hasStream: false,
    hasSecurity: false,
    hasSniffing: false,
    description: "WireGuard VPN inbound",
  },
  {
    id: "hysteria",
    label: "Hysteria2",
    icon: "Wind",
    category: "advanced",
    hasUsers: true,
    hasStream: false,
    hasSecurity: true,
    hasSniffing: true,
    description: "QUIC-based Hysteria2 protocol (TLS required)",
  },
  {
    id: "amneziawg",
    label: "AmneziaWG",
    icon: "Radio",
    category: "advanced",
    hasUsers: false,
    hasStream: false,
    hasSecurity: false,
    hasSniffing: false,
    description: "AmneziaWG variant of WireGuard",
  },
  {
    id: "tun",
    label: "TUN",
    icon: "Satellite",
    category: "advanced",
    hasUsers: false,
    hasStream: false,
    hasSecurity: false,
    hasSniffing: false,
    description: "Virtual network interface inbound",
  },
  {
    id: "dokodemo-door",
    label: "Dokodemo",
    icon: "DoorOpen",
    category: "advanced",
    hasUsers: false,
    hasStream: true,
    hasSecurity: true,
    hasSniffing: true,
    description: "Transparent proxy / port forward (dokodemo-door)",
  },
];
