services:
  nexuspanel:
    build: .
    restart: always
    env_file: .env
    network_mode: host
    group_add:
      - "${DOCKER_GID:-988}"
    volumes:
      - /var/lib/nexuspanel:/var/lib/nexuspanel
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
