from fastapi import APIRouter

from . import (
    admin,
    analytics,
    api_keys,
    backup,
    billing,
    client_v2,
    core,
    dedicated_ip,
    feature_flags,
    home,
    panel_system,
    platform_settings,
    portal,
    user_import,
    intelligence,
    marketplace,
    metrics,
    node,
    plans,
    plugins,
    protocols,
    provisioning,
    reseller,
    routing,
    rules,
    setup,
    subscription,
    system,
    tenant,
    tunnel,
    user,
    user_template,
    v2,
    workflows,
)

api_router = APIRouter()

routers = [
    admin.router,
    analytics.router,
    api_keys.router,
    backup.router,
    billing.router,
    client_v2.router,
    core.router,
    dedicated_ip.router,
    feature_flags.router,
    panel_system.router,
    platform_settings.router,
    portal.router,
    user_import.router,
    intelligence.router,
    marketplace.router,
    metrics.router,
    node.router,
    plans.router,
    plugins.router,
    protocols.router,
    provisioning.router,
    reseller.router,
    routing.router,
    rules.router,
    setup.router,
    subscription.router,
    system.router,
    tenant.router,
    tunnel.router,
    user_template.router,
    user.router,
    v2.router,
    workflows.router,
    home.router,
]

for router in routers:
    api_router.include_router(router)

__all__ = ["api_router"]