#!/usr/bin/env bash
#
# NexusPanel installer & manager.
#
# One-line install (run as root):
#   bash <(curl -fsSL https://raw.githubusercontent.com/KhaJehAmiri/nexuspanel/master/scripts/nexuspanel.sh) install
#
# After install, manage with:  nexuspanel <command>
#   install | update | up | down | restart | status | logs
#   backup | restore <file> | cli ... | uninstall
#
set -euo pipefail

# --------------------------------------------------------------------------- #
# Config (override via env)
# --------------------------------------------------------------------------- #
APP_NAME="nexuspanel"
APP_DIR="${APP_DIR:-/opt/nexuspanel}"
DATA_DIR="${DATA_DIR:-/var/lib/nexuspanel}"
REPO_URL="${REPO_URL:-https://github.com/KhaJehAmiri/nexuspanel.git}"
REPO_BRANCH="${REPO_BRANCH:-master}"
PANEL_PORT="${PANEL_PORT:-8000}"
SCRIPT_URL="${SCRIPT_URL:-https://raw.githubusercontent.com/KhaJehAmiri/nexuspanel/${REPO_BRANCH}/scripts/nexuspanel.sh}"
BIN_PATH="/usr/local/bin/${APP_NAME}"

# Colours
RED=$'\e[31m'; GREEN=$'\e[32m'; YELLOW=$'\e[33m'; BLUE=$'\e[34m'; BOLD=$'\e[1m'; NC=$'\e[0m'

log()  { echo "${BLUE}[*]${NC} $*"; }
ok()   { echo "${GREEN}[✓]${NC} $*"; }
warn() { echo "${YELLOW}[!]${NC} $*"; }
err()  { echo "${RED}[x]${NC} $*" >&2; }
die()  { err "$*"; exit 1; }

need_root() {
  [ "$(id -u)" -eq 0 ] || die "Please run as root (sudo)."
}

rand() { head -c "${1:-32}" /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c "${1:-32}"; }

compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose -f "${APP_DIR}/docker-compose.yml" "$@"
  else
    docker-compose -f "${APP_DIR}/docker-compose.yml" "$@"
  fi
}

# --------------------------------------------------------------------------- #
# Dependencies
# --------------------------------------------------------------------------- #
install_deps() {
  if ! command -v curl >/dev/null 2>&1; then
    log "Installing curl..."
    (apt-get update -y && apt-get install -y curl) >/dev/null 2>&1 || \
      (yum install -y curl) >/dev/null 2>&1 || true
  fi
  if ! command -v git >/dev/null 2>&1; then
    log "Installing git..."
    (apt-get install -y git) >/dev/null 2>&1 || (yum install -y git) >/dev/null 2>&1 || true
  fi
  if ! command -v docker >/dev/null 2>&1; then
    log "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker >/dev/null 2>&1 || true
    ok "Docker installed."
  fi
}

# --------------------------------------------------------------------------- #
# .env generation (interactive but with sane non-interactive defaults)
# --------------------------------------------------------------------------- #
write_env() {
  local env_file="${APP_DIR}/.env"
  if [ -f "$env_file" ]; then
    warn ".env already exists; keeping it."
    return
  fi

  local admin_user admin_pass
  admin_user="${ADMIN_USERNAME:-admin}"
  admin_pass="${ADMIN_PASSWORD:-$(rand 16)}"

  log "Generating configuration..."
  cat > "$env_file" <<EOF
# Generated by nexuspanel installer on $(date -u +%FT%TZ)
SUDO_USERNAME=${admin_user}
SUDO_PASSWORD=${admin_pass}

UVICORN_HOST=0.0.0.0
UVICORN_PORT=${PANEL_PORT}

SQLALCHEMY_DATABASE_URL=sqlite:////var/lib/nexuspanel/db.sqlite3
XRAY_JSON=/var/lib/nexuspanel/xray_config.json

# Secrets
JWT_SECRET=$(rand 48)
NODE_BOOTSTRAP_TOKEN=$(rand 40)

# Phase 6: address resellers' provisioned nodes use to reach this panel.
PANEL_PUBLIC_ADDRESS=$(curl -fsSL https://api.ipify.org 2>/dev/null || echo "127.0.0.1"):${PANEL_PORT}

# Backups
BACKUP_DIR=/var/lib/nexuspanel/backups
BACKUP_INTERVAL_HOURS=24

# Node agent image (built by installer if node/Dockerfile exists)
NODE_AGENT_IMAGE=nexuspanel/node:latest
EOF
  chmod 600 "$env_file"

  # Stash creds so we can print them at the end.
  ADMIN_USERNAME="$admin_user"
  ADMIN_PASSWORD="$admin_pass"
  export ADMIN_USERNAME ADMIN_PASSWORD
}

fetch_repo() {
  if [ -d "${APP_DIR}/.git" ]; then
    log "Updating ${APP_NAME} source..."
    git -C "${APP_DIR}" fetch --depth 1 origin "${REPO_BRANCH}" >/dev/null 2>&1
    git -C "${APP_DIR}" reset --hard "origin/${REPO_BRANCH}" >/dev/null 2>&1
  else
    log "Fetching ${APP_NAME} source into ${APP_DIR}..."
    mkdir -p "$(dirname "${APP_DIR}")"
    git clone --depth 1 -b "${REPO_BRANCH}" "${REPO_URL}" "${APP_DIR}" >/dev/null 2>&1 \
      || die "Failed to clone ${REPO_URL}. Set REPO_URL to a reachable repository."
  fi
}

install_cli() {
  log "Installing 'nexuspanel' command..."
  curl -fsSL "${SCRIPT_URL}" -o "${BIN_PATH}" 2>/dev/null || cp "$0" "${BIN_PATH}" 2>/dev/null || true
  chmod +x "${BIN_PATH}" 2>/dev/null || true
}

build_node_image() {
  if [ ! -f "${APP_DIR}/node/Dockerfile" ]; then
    warn "node/Dockerfile not found; skip node-agent image build."
    return
  fi
  log "Building nexuspanel/node agent image (SSH provisioning)..."
  if docker build -t nexuspanel/node:latest "${APP_DIR}/node"; then
    ok "Node image: nexuspanel/node:latest"
  else
    warn "Node image build failed. Build manually: docker build -t nexuspanel/node:latest ${APP_DIR}/node"
  fi
}

wait_for_panel() {
  local url="http://127.0.0.1:${PANEL_PORT}/api/setup/status"
  log "Waiting for panel API..."
  for _ in $(seq 1 45); do
    if curl -sf "$url" >/dev/null 2>&1; then
      ok "Panel API is up."
      return 0
    fi
    sleep 2
  done
  warn "Panel API did not respond in time. Check: nexuspanel logs"
}

# --------------------------------------------------------------------------- #
# Commands
# --------------------------------------------------------------------------- #
cmd_install() {
  need_root
  echo "${BOLD}Installing NexusPanel...${NC}"
  install_deps
  fetch_repo
  mkdir -p "${DATA_DIR}" "${DATA_DIR}/backups"
  write_env
  install_cli
  log "Building and starting panel (first run may take a few minutes)..."
  compose up -d --build
  build_node_image
  wait_for_panel
  ok "NexusPanel is up."
  print_access
}

print_access() {
  local ip; ip="$(curl -fsSL https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')"
  echo
  echo "${BOLD}${GREEN}==== NexusPanel ready ====${NC}"
  echo "  Dashboard : ${BOLD}http://${ip}:${PANEL_PORT}/dashboard/${NC}"
  if [ -n "${ADMIN_USERNAME:-}" ]; then
    echo "  Username  : ${BOLD}${ADMIN_USERNAME}${NC}"
    echo "  Password  : ${BOLD}${ADMIN_PASSWORD}${NC}"
    echo "  ${YELLOW}Save these credentials now.${NC}"
  fi
  echo "  Manage    : ${BOLD}nexuspanel status | logs | update | backup${NC}"
  echo "  White-label: ${BOLD}http://${ip}:${PANEL_PORT}/dashboard/#/manage/${NC}"
  echo "  ${YELLOW}First login → Setup wizard (enable tenants, provisioning, tunnels).${NC}"
  echo
}

cmd_update()  { need_root; fetch_repo; compose up -d --build; ok "Updated."; }
cmd_up()      { need_root; compose up -d; ok "Started."; }
cmd_down()    { need_root; compose down; ok "Stopped."; }
cmd_restart() { need_root; compose restart; ok "Restarted."; }
cmd_status()  { compose ps; }
cmd_logs()    { compose logs -f --tail=200; }
cmd_cli()     { need_root; compose exec -T ${APP_NAME} nexuspanel-cli "$@"; }

cmd_backup() {
  need_root
  local ts out; ts="$(date -u +%Y%m%d-%H%M%S)"; out="${DATA_DIR}/backups/backup-${ts}.tar.gz"
  log "Creating backup..."
  # Archive the data dir (db, xray config) plus the .env, excluding old backups.
  tar -czf "${out}" \
    -C "${DATA_DIR}" --exclude='./backups' . \
    -C "${APP_DIR}" .env 2>/dev/null || tar -czf "${out}" -C "${DATA_DIR}" --exclude='./backups' .
  ok "Backup written to ${out}"
}

cmd_restore() {
  need_root
  local file="${1:-}"; [ -n "$file" ] && [ -f "$file" ] || die "Usage: nexuspanel restore <backup.tar.gz>"
  warn "Restoring will overwrite current data."
  compose down || true
  tar -xzf "$file" -C "${DATA_DIR}"
  compose up -d
  ok "Restored from ${file}"
}

cmd_uninstall() {
  need_root
  read -r -p "${YELLOW}Remove NexusPanel and ALL data? [y/N]: ${NC}" ans
  case "${ans:-N}" in
    y|Y)
      compose down -v 2>/dev/null || true
      rm -rf "${APP_DIR}" "${BIN_PATH}"
      warn "Kept ${DATA_DIR} (your data). Remove it manually if you really want to."
      ok "Uninstalled."
      ;;
    *) log "Aborted." ;;
  esac
}

usage() {
  cat <<EOF
${BOLD}NexusPanel manager${NC}

Usage: ${APP_NAME} <command>

  install            Install and start NexusPanel
  update             Pull latest and rebuild
  up | down | restart
  status             Show container status
  logs               Tail logs
  backup             Create a backup archive
  restore <file>     Restore from a backup archive
  cli <args...>      Run nexuspanel-cli inside the container
  uninstall          Remove the app (keeps data dir)
EOF
}

main() {
  local cmd="${1:-install}"; shift || true
  case "$cmd" in
    install)   cmd_install "$@";;
    update)    cmd_update "$@";;
    up)        cmd_up "$@";;
    down)      cmd_down "$@";;
    restart)   cmd_restart "$@";;
    status)    cmd_status "$@";;
    logs)      cmd_logs "$@";;
    backup)    cmd_backup "$@";;
    restore)   cmd_restore "$@";;
    cli)       cmd_cli "$@";;
    uninstall) cmd_uninstall "$@";;
    -h|--help|help) usage;;
    *) usage; exit 1;;
  esac
}

main "$@"
